# Generated by Django 4.0.6 on 2022-08-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
